const functions = require("firebase-functions");
const { EleventyServerless } = require("@11ty/eleventy");

// Explicit dependencies for the bundler from config file and global data.
// The file is generated by the Eleventy Serverless Bundler Plugin.
require("./eleventy-bundler-modules.js");

exports.handler = functions.https.onRequest(async (request, response) => {
  functions.logger.info("Hello eleventy serverless!", { structuredData: true });

  let elev = new EleventyServerless("possum", {
    path: request.path,
    inputDir: ".",
    functionsDir: "./functions/possum/",
  });

  try {
    const body = await elev.render();
    return response.send(body);
  } catch (error) {
    if (elev.isServerlessUrl(request.event.path)) {
      console.log("Serverless Error:", error);
    }

    return response.status(500).send(
      JSON.stringify(
        {
          error: error.message,
        },
        null,
        2
      )
    );
  }
});
